name: Build Project

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build & upload hex
    steps:
      - uses: actions/checkout@v4
      - name: Build all projects
        run: docker run -v $(pwd):/home --rm ghcr.io/microbit-foundation/daplink:2022.01.1 python build_all.py
      - name: Upload Radio Bridge hex file
        uses: actions/upload-artifact@v4
        with:
          name: radio-bridge
          path: radio-bridge.hex
      - name: Upload Radio Bridge Dev hex file
        uses: actions/upload-artifact@v4
        with:
          name: radio-bridge-dev
          path: radio-bridge-dev.hex
      - name: Upload Radio Remote hex file
        uses: actions/upload-artifact@v4
        with:
          name: radio-remote
          path: radio-remote.hex
      - name: Upload Radio Remote Dev hex file
        uses: actions/upload-artifact@v4
        with:
          name: radio-remote-dev
          path: radio-remote-dev.hex
      - name: Upload Local Sensors hex file
        uses: actions/upload-artifact@v4
        with:
          name: local-sensors
          path: local-sensors.hex
